"""
Authentication module for Apple Music API.

Apple Music uses a two-token system:
  1. Developer Token  — a JWT you sign with your MusicKit private key (.p8).
                        Valid up to 6 months; auto-regenerated by this module.
  2. Music User Token — obtained once via MusicKit JS in a browser.
                        Stored in ~/.config/mcp-apple-music/config.json.

Configuration can be provided via:
  - Config file: ~/.config/mcp-apple-music/config.json  (default)
  - Environment variables (useful for Docker / CI):
      APPLE_TEAM_ID            Your Apple Developer Team ID
      APPLE_KEY_ID             Your MusicKit Key ID
      APPLE_PRIVATE_KEY        Full content of your .p8 private key
      APPLE_MUSIC_USER_TOKEN   Your Music User Token
      APPLE_STOREFRONT         App Store storefront (default: us)
"""

import json
import os
import time
from pathlib import Path
from typing import Optional

import jwt  # PyJWT

DEFAULT_CONFIG_PATH = Path.home() / ".config" / "mcp-apple-music" / "config.json"


class AppleMusicAuth:
    """Manages Developer Token generation and Music User Token retrieval."""

    def __init__(self, config_path: Path = DEFAULT_CONFIG_PATH):
        self.config_path = Path(config_path)
        self._config: Optional[dict] = None
        self._developer_token: Optional[str] = None
        self._token_expiry: float = 0

    # ------------------------------------------------------------------ #
    #  Config                                                              #
    # ------------------------------------------------------------------ #

    @property
    def config(self) -> dict:
        if self._config is None:
            self._config = self._load_config()
        return self._config

    def _load_config(self) -> dict:
        """Load config from environment variables first, then fall back to file."""
        # Try environment variables first (Docker / CI friendly)
        env_team_id = os.environ.get("APPLE_TEAM_ID", "").strip()
        env_key_id = os.environ.get("APPLE_KEY_ID", "").strip()
        env_private_key = os.environ.get("APPLE_PRIVATE_KEY", "").strip()
        env_user_token = os.environ.get("APPLE_MUSIC_USER_TOKEN", "").strip()
        env_storefront = os.environ.get("APPLE_STOREFRONT", "").strip()

        if env_team_id and env_key_id and env_private_key:
            return {
                "team_id": env_team_id,
                "key_id": env_key_id,
                "private_key_content": env_private_key,  # key content, not path
                "music_user_token": env_user_token,
                "storefront": env_storefront or "us",
            }

        # Fall back to config file
        if not self.config_path.exists():
            raise FileNotFoundError(
                f"\n❌  Config not found: {self.config_path}\n"
                "    Run the setup wizard first:\n\n"
                "        mcp-apple-music-setup\n\n"
                "    Or set environment variables:\n"
                "        APPLE_TEAM_ID, APPLE_KEY_ID, APPLE_PRIVATE_KEY,\n"
                "        APPLE_MUSIC_USER_TOKEN, APPLE_STOREFRONT\n"
            )
        with open(self.config_path) as f:
            return json.load(f)

    # ------------------------------------------------------------------ #
    #  Developer Token (JWT)                                               #
    # ------------------------------------------------------------------ #

    def get_developer_token(self) -> str:
        """Return a valid Developer Token, generating a new one if needed."""
        now = time.time()
        # Regenerate when expired or within 5 minutes of expiry
        if self._developer_token and now < self._token_expiry - 300:
            return self._developer_token

        # Support both inline key content (env var) and file path (config.json)
        private_key_content = self.config.get("private_key_content")
        if private_key_content:
            private_key = private_key_content.replace("\\n", "\n")
        else:
            key_path = Path(self.config["private_key_path"]).expanduser()
            if not key_path.exists():
                raise FileNotFoundError(f"MusicKit private key not found: {key_path}")
            with open(key_path) as f:
                private_key = f.read()

        expiry = int(now) + 15_777_000  # ≈ 6 months

        self._developer_token = jwt.encode(
            payload={
                "iss": self.config["team_id"],
                "iat": int(now),
                "exp": expiry,
            },
            key=private_key,
            algorithm="ES256",
            headers={"kid": self.config["key_id"]},
        )
        self._token_expiry = expiry
        return self._developer_token

    # ------------------------------------------------------------------ #
    #  Music User Token                                                    #
    # ------------------------------------------------------------------ #

    def get_music_user_token(self) -> str:
        """Return the Music User Token stored in config."""
        token = self.config.get("music_user_token", "")
        if not token:
            raise ValueError(
                "\n❌  Music User Token missing.\n"
                "    Run the setup wizard to authorise your Apple Music account:\n\n"
                "        mcp-apple-music-setup\n\n"
                "    Or set the APPLE_MUSIC_USER_TOKEN environment variable.\n"
            )
        return token

    # ------------------------------------------------------------------ #
    #  Helpers                                                             #
    # ------------------------------------------------------------------ #

    def get_storefront(self) -> str:
        """Return the two-letter storefront country code (e.g. 'it', 'us')."""
        return self.config.get("storefront", "us")

    def get_auth_headers(self) -> dict[str, str]:
        """Return the HTTP headers required by every Apple Music API request."""
        return {
            "Authorization": f"Bearer {self.get_developer_token()}",
            "Music-User-Token": self.get_music_user_token(),
        }

    def get_catalog_headers(self) -> dict[str, str]:
        """Headers for catalog-only requests (no user token required)."""
        return {"Authorization": f"Bearer {self.get_developer_token()}"}
